/// <reference path="../progressivedifficultywordle/typescript/models/eligiblewords.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/gameoptions.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/gametype.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/letterstate.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/letterstatus.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/scoredetails.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/session.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/sessionstate.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/guessdetails.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/singlegame.ts" />
/// <reference path="../progressivedifficultywordle/typescript/constants/words/fiveletteranswers.ts" />
/// <reference path="../progressivedifficultywordle/typescript/constants/words/fiveletterguesses.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/notification/notificationeventing.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/notification/notificationtype.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/notification/notificationwrapper.ts" />
//# sourceMappingURL=PDWIndex.js.map