/// <reference path="../progressivedifficultywordle/typescript/models/eligiblewords.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/gameoptions.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/gametype.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/letterstate.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/letterstatus.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/scoredetails.ts" />
/// <reference path="../progressivedifficultywordle/typescript/models/session.ts" />
/// <reference path="../progressivedifficultywordle/typescript/constants/words/fiveletteranswers.ts" />
/// <reference path="../progressivedifficultywordle/typescript/constants/words/fiveletterguesses.ts" />
//# sourceMappingURL=PDWIndex.js.map